import person1 from "../../public/profilePics/ankit.jpg";

export const TeamData = [
  {
    id: 1,
    domain: 1,
    year: 4,
    cardName: "Person 1",
    cardDesignation: "Web Developer",
    image: person1,
    links: {
      github: "/",
      linkedin: "/",
      instagram: "/",
      behance: "/",
    },
  },
  {
    id: 2,
    year: 4,
    domain: 1,
    cardName: "Person 1",
    cardDesignation: "Web Developer",
    image: person1,
    links: {
      github: "/",
      linkedin: "/",
      instagram: "/",
      behance: "/",
    },
  },
  {
    id: 3,
    year: 3,
    domain: 2,
    cardName: "Person 1",
    cardDesignation: "Machine Learning",
    image: person1,
    links: {
      github: "/",
      linkedin: "/",
      instagram: "/",
      behance: "/",
    },
  },
  {
    id: 4,
    year: 3,
    domain: 3,
    cardName: "Person 1",
    cardDesignation: "App Developer",
    image: person1,
    links: {
      github: "/",
      linkedin: "/",
      instagram: "/",
      behance: "/",
    },
  },
  {
    id: 5,
    year: 3,
    domain: 3,
    cardName: "Person 1",
    cardDesignation: "App Developer",
    image: person1,
    links: {
      github: "/",
      linkedin: "/",
      instagram: "/",
      behance: "/",
    },
  },
  {
    id: 6,
    year: 3,
    domain: 2,
    cardName: "Person 1",
    cardDesignation: "Machine Learning",
    image: person1,
    links: {
      github: "/",
      linkedin: "/",
      instagram: "/",
      behance: "/",
    },
  },
  {
    id: 7,
    year: 3,
    domain: 1,
    cardName: "Person 1",
    cardDesignation: "Web Developer",
    image: person1,
    links: {
      github: "/",
      linkedin: "/",
      instagram: "/",
      behance: "/",
    },
  },
  {
    id: 8,
    year: 3,
    domain: 4,
    cardName: "Person 1",
    cardDesignation: "Management",
    image: person1,
    links: {
      github: "/",
      linkedin: "/",
      instagram: "/",
      behance: "/",
    },
  },
  {
    id: 9,
    year: 3,
    domain: 4,
    cardName: "Person 1",
    cardDesignation: "Management",
    image: person1,
    links: {
      github: "/",
      linkedin: "/",
      instagram: "/",
      behance: "/",
    },
  },
  {
    id: 10,
    year: 3,
    domain: 2,
    cardName: "Person 1",
    cardDesignation: "Machine Learning",
    image: person1,
    links: {
      github: "/",
      linkedin: "/",
      instagram: "/",
      behance: "/",
    },
  },
];
