import Nav from '@/components/Nav';
import Head from 'next/head';

export default function Home() {
  return (
    <>
      <Head>
        <title>Google Developer Students Clubs - FETJU</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/gdsc.png" />
      </Head>
      <main>
        {/* NavBar */}
        <Nav />
        {/* Hero Section */}
        {/* Info about events / students */}
        {/* Our Team */}
        {/* Past Events */}
        {/* Testimonials */}
        {/* Collaborations */}
        {/* Idea discussion */}
        {/* Footer Section */}
      </main>
    </>
  );
}
