import Head from 'next/head';

export default function Home() {
  return (
    <>
      <Head>
        <title>Google Developer Students Clubs - FETJU</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/gdsc.png" />
      </Head>
      <main>
        <h1 className="text-pink-500 text-6xl text-center">
          Google Developer Students Clubs - FETJU
        </h1>
      </main>
    </>
  );
}
